export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';